#### This project involves a classification task where the objective is to predict whether a company's net worth will 
#### increase or decrease in the next year based on previous year data.

##### Importing libraries for EDA and Data Visualization

In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

##### Reading the data

In [57]:
data = pd.read_csv(r"C:\Users\Umang Agarwal\OneDrive\Desktop\Pandas Dataset\Banking_Finance_data.csv")

In [58]:
data.head()

,Num,Networth Next Year,Total assets,Net worth,Total income,Change in stock,Total expenses,Profit after tax,PBDITA,PBT,...,Debtors turnover,Finished goods turnover,WIP turnover,Raw material turnover,Shares outstanding,Equity face value,EPS,Adjusted EPS,Total liabilities,PE on BSE
0,1,8890.6,17512.3,7093.2,24965.2,235.8,23657.8,1543.2,2860.2,2417.2,...,3.85,200.55,21.78,7.71,42381675.0,10.0,35.52,7.10,17512.3,27.31
1,2,394.3,941.0,351.5,1527.4,42.7,1454.9,115.2,283.0,188.4,...,5.70,14.21,7.49,11.46,11550000.0,10.0,9.97,9.97,941.0,8.17
2,3,92.2,232.8,100.6,477.3,-5.2,478.7,-6.6,5.8,-6.6,...,5.07,9.24,0.23,NaN,8149090.0,10.0,-0.50,-0.50,232.8,-5.76
3,4,2.7,2.7,2.7,NaN,NaN,NaN,NaN,NaN,NaN,...,0.00,NaN,NaN,0.00,52404.0,10.0,0.00,0.00,2.7,NaN
4,5,109.0,478.5,107.6,1580.5,-17.0,1558.0,5.5,31.0,6.3,...,9.46,12.68,7.90,17.03,619635.0,10.0,7.91,7.91,478.5,NaN

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3541 entries, 0 to 3540
Data columns (total 52 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Num                                          3541 non-null   int64
 1   Networth Next Year                           3541 non-null   float64
 2   Total assets                                 3541 non-null   float64
 3   Net worth                                    3541 non-null   float64
 4   Total income                                 3343 non-null   float64
 5   Change in stock                              3083 non-null   float64
 6   Total expenses                               3402 non-null   float64
 7   Profit after tax                             3410 non-null   float64
 8   PBDITA                                       3410 non-null   float64
 9   PBT                                          3410 non-null   float64
 10  Cash profit                                  3410 non-null   float64
 11  PBDITA as % of total income                  3473 non-null   float64
 12  PBT as % of total income                     3473 non-null   float64
 13  PAT as % of total income                     3473 non-null   float64
 14  Cash profit as % of total income             3473 non-null   float64
 15  PAT as % of net worth                        3541 non-null   float64
 16  Sales                                        3282 non-null   float64
 17  Income from financial services               2606 non-null   float64
 18  Other income                                 2246 non-null   float64
 19  Total capital                                3537 non-null   float64
 20  Reserves and funds                           3456 non-null   float64
 21  Deposits (accepted by commercial banks)      0 non-null      float64
 22  Borrowings                                   3175 non-null   float64
 23  Current liabilities & provisions             3445 non-null   float64
 24  Deferred tax liability                       2401 non-null   float64
 25  Shareholders funds                           3541 non-null   float64
 26  Cumulative retained profits                  3503 non-null   float64
 27  Capital employed                             3541 non-null   float64
 28  TOL/TNW                                      3541 non-null   float64
 29  Total term liabilities / tangible net worth  3541 non-null   float64
 30  Contingent liabilities / Net worth (%)       3541 non-null   float64
 31  Contingent liabilities                       2353 non-null   float64
 32  Net fixed assets                             3423 non-null   float64
 33  Investments                                  2106 non-null   float64
 34  Current assets                               3475 non-null   float64
 35  Net working capital                          3509 non-null   float64
 36  Quick ratio (times)                          3448 non-null   float64
 37  Current ratio (times)                        3448 non-null   float64
 38  Debt to equity ratio (times)                 3541 non-null   float64
 39  Cash to current liabilities (times)          3448 non-null   float64
 40  Cash to average cost of sales per day        3456 non-null   float64
 41  Creditors turnover                           3208 non-null   float64
 42  Debtors turnover                             3213 non-null   float64
 43  Finished goods turnover                      2801 non-null   float64
 44  WIP turnover                                 2901 non-null   float64
 45  Raw material turnover                        3180 non-null   float64
 46  Shares outstanding                           2849 non-null   float64
 47  Equity face value                            2849 non-null   float64
 48  EPS                                          3541 non-null   float64
 49  Adjusted EPS                                 3541 non-null   float64
 50  Total liabilities                            3541 non-null   float64
 51  PE on BSE                                    1347 non-null   float64
dtypes: float64(51), int64(1)
memory usage: 1.4 MB

In [60]:
data.shape

(3541, 52)

In [61]:
data.columns

Index(['Num', 'Networth Next Year', 'Total assets', 'Net worth',
       'Total income', 'Change in stock', 'Total expenses', 'Profit after tax',
       'PBDITA', 'PBT', 'Cash profit', 'PBDITA as % of total income',
       'PBT as % of total income', 'PAT as % of total income',
       'Cash profit as % of total income', 'PAT as % of net worth', 'Sales',
       'Income from financial services', 'Other income', 'Total capital',
       'Reserves and funds', 'Deposits (accepted by commercial banks)',
       'Borrowings', 'Current liabilities & provisions',
       'Deferred tax liability', 'Shareholders funds',
       'Cumulative retained profits', 'Capital employed', 'TOL/TNW',
       'Total term liabilities / tangible net worth',
       'Contingent liabilities / Net worth (%)', 'Contingent liabilities',
       'Net fixed assets', 'Investments', 'Current assets',
       'Net working capital', 'Quick ratio (times)', 'Current ratio (times)',
       'Debt to equity ratio (times)', 'Cash to current liabilities (times)',
       'Cash to average cost of sales per day', 'Creditors turnover',
       'Debtors turnover', 'Finished goods turnover', 'WIP turnover',
       'Raw material turnover', 'Shares outstanding', 'Equity face value',
       'EPS', 'Adjusted EPS', 'Total liabilities', 'PE on BSE'],
      dtype='object')

In [62]:
data.describe()

,Num,Networth Next Year,Total assets,Net worth,Total income,Change in stock,Total expenses,Profit after tax,PBDITA,PBT,...,Debtors turnover,Finished goods turnover,WIP turnover,Raw material turnover,Shares outstanding,Equity face value,EPS,Adjusted EPS,Total liabilities,PE on BSE
count,3541.000000,3541.000000,3.541000e+03,3541.000000,3.343000e+03,3083.000000,3.402000e+03,3410.00000,3410.000000,3410.000000,...,3213.000000,2801.000000,2901.000000,3180.000000,2.849000e+03,2849.000000,3541.000000,3541.000000,3.541000e+03,1347.000000
mean,1772.451567,1616.256199,3.443382e+03,1295.862214,4.582823e+03,41.489264,4.262931e+03,277.36044,578.056305,383.810088,...,17.041261,87.078725,27.930469,19.088399,2.206739e+07,-1333.698175,-220.316436,-221.512285,3.443382e+03,63.905687
std,1023.731393,17459.639673,3.097089e+04,13387.891867,5.568124e+04,440.573761,5.302869e+04,3064.40606,5653.770427,4117.069953,...,83.943754,598.545835,151.042868,376.340737,1.655193e+08,37500.729972,14261.946209,14261.923760,3.097089e+04,1433.809532
min,1.000000,-74265.600000,1.000000e-01,0.000000,0.000000e+00,-3029.400000,-1.000000e-01,-3908.30000,-440.700000,-3894.800000,...,0.000000,-0.090000,-0.180000,-2.000000,-2.147484e+09,-999998.900000,-843181.820000,-843181.820000,1.000000e-01,-1116.640000
25%,886.000000,31.700000,9.130000e+01,31.300000,1.064500e+02,-1.800000,9.582500e+01,0.50000,6.900000,0.700000,...,3.760000,8.200000,5.100000,2.990000,1.316250e+06,10.000000,0.000000,0.000000,9.130000e+01,3.275000
50%,1773.000000,116.300000,3.097000e+02,102.300000,4.449000e+02,1.600000,4.077000e+02,8.80000,35.400000,12.400000,...,6.320000,17.270000,9.760000,6.400000,4.672063e+06,10.000000,1.430000,1.180000,3.097000e+02,9.100000
75%,2658.000000,456.100000,1.098700e+03,377.300000,1.440900e+03,18.050000,1.359775e+03,52.27500,150.250000,71.975000,...,11.680000,40.350000,20.240000,11.845000,1.065197e+07,10.000000,9.620000,7.480000,1.098700e+03,17.790000
max,3545.000000,805773.400000,1.176509e+06,613151.600000,2.442828e+06,14185.500000,2.366035e+06,119439.10000,208576.500000,145292.600000,...,3135.200000,17947.600000,5651.400000,21092.000000,4.130401e+09,100000.000000,34522.530000,34522.530000,1.176509e+06,51002.740000

In [63]:
data.duplicated().sum()

0

In [64]:
data.dtypes

Num                                              int64
Networth Next Year                             float64
Total assets                                   float64
Net worth                                      float64
Total income                                   float64
Change in stock                                float64
Total expenses                                 float64
Profit after tax                               float64
PBDITA                                         float64
PBT                                            float64
Cash profit                                    float64
PBDITA as % of total income                    float64
PBT as % of total income                       float64
PAT as % of total income                       float64
Cash profit as % of total income               float64
PAT as % of net worth                          float64
Sales                                          float64
Income from financial services                 float64
Other income                                   float64
Total capital                                  float64
Reserves and funds                             float64
Deposits (accepted by commercial banks)        float64
Borrowings                                     float64
Current liabilities & provisions               float64
Deferred tax liability                         float64
Shareholders funds                             float64
Cumulative retained profits                    float64
Capital employed                               float64
TOL/TNW                                        float64
Total term liabilities / tangible net worth    float64
Contingent liabilities / Net worth (%)         float64
Contingent liabilities                         float64
Net fixed assets                               float64
Investments                                    float64
Current assets                                 float64
Net working capital                            float64
Quick ratio (times)                            float64
Current ratio (times)                          float64
Debt to equity ratio (times)                   float64
Cash to current liabilities (times)            float64
Cash to average cost of sales per day          float64
Creditors turnover                             float64
Debtors turnover                               float64
Finished goods turnover                        float64
WIP turnover                                   float64
Raw material turnover                          float64
Shares outstanding                             float64
Equity face value                              float64
EPS                                            float64
Adjusted EPS                                   float64
Total liabilities                              float64
PE on BSE                                      float64
dtype: object

In [65]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Num,3541.0,1.772452e+03,1.023731e+03,1.000000e+00,886.000,1773.000,2.658000e+03,3.545000e+03
Networth Next Year,3541.0,1.616256e+03,1.745964e+04,-7.426560e+04,31.700,116.300,4.561000e+02,8.057734e+05
Total assets,3541.0,3.443382e+03,3.097089e+04,1.000000e-01,91.300,309.700,1.098700e+03,1.176509e+06
Net worth,3541.0,1.295862e+03,1.338789e+04,0.000000e+00,31.300,102.300,3.773000e+02,6.131516e+05
Total income,3343.0,4.582823e+03,5.568124e+04,0.000000e+00,106.450,444.900,1.440900e+03,2.442828e+06
Change in stock,3083.0,4.148926e+01,4.405738e+02,-3.029400e+03,-1.800,1.600,1.805000e+01,1.418550e+04
Total expenses,3402.0,4.262931e+03,5.302869e+04,-1.000000e-01,95.825,407.700,1.359775e+03,2.366035e+06
Profit after tax,3410.0,2.773604e+02,3.064406e+03,-3.908300e+03,0.500,8.800,5.227500e+01,1.194391e+05
PBDITA,3410.0,5.780563e+02,5.653770e+03,-4.407000e+02,6.900,35.400,1.502500e+02,2.085765e+05
PBT,3410.0,3.838101e+02,4.117070e+03,-3.894800e+03,0.700,12.400,7.197500e+01,1.452926e+05
Cash profit,3410.0,3.920650e+02,4.226641e+03,-2.245700e+03,2.900,18.850,9.320000e+01,1.769118e+05
PBDITA as % of total income,3473.0,4.570639e+00,1.471220e+02,-6.400000e+03,5.000,9.660,1.639000e+01,1.000000e+02
PBT as % of total income,3473.0,-1.727902e+01,4.254338e+02,-2.134000e+04,0.550,3.310,8.800000e+00,1.000000e+02
PAT as % of total income,3473.0,-1.919996e+01,4.298113e+02,-2.134000e+04,0.350,2.340,6.340000e+00,1.500000e+02
Cash profit as % of total income,3473.0,-8.229177e+00,3.045662e+02,-1.502000e+04,2.020,5.640,1.070000e+01,1.000000e+02
PAT as % of net worth,3541.0,1.026928e+01,6.514821e+01,-7.487200e+02,0.000,7.920,2.019000e+01,2.466670e+03
Sales,3282.0,4.549520e+03,5.496465e+04,1.000000e-01,112.675,453.100,1.433550e+03,2.384984e+06
Income from financial services,2606.0,8.084359e+01,1.115168e+03,0.000000e+00,0.400,1.800,9.675000e+00,5.193820e+04
Other income,2246.0,4.135672e+01,9.172901e+02,0.000000e+00,0.400,1.400,5.975000e+00,4.285670e+04
Total capital,3537.0,2.166090e+02,1.682590e+03,1.000000e-01,13.100,42.100,1.003000e+02,7.827320e+04
Reserves and funds,3456.0,1.163815e+03,1.337268e+04,-6.525900e+03,5.000,54.800,2.773000e+02,6.251378e+05
Deposits (accepted by commercial banks),0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Borrowings,3175.0,1.122279e+03,8.681918e+03,1.000000e-01,23.950,99.200,3.526000e+02,2.782573e+05
Current liabilities & provisions,3445.0,9.406269e+02,9.546090e+03,1.000000e-01,17.800,69.400,2.617000e+02,3.522403e+05
Deferred tax liability,2401.0,2.272162e+02,2.170211e+03,1.000000e-01,3.200,13.400,5.000000e+01,7.279660e+04
Shareholders funds,3541.0,1.322068e+03,1.344529e+04,0.000000e+00,32.000,105.600,3.932000e+02,6.131516e+05
Cumulative retained profits,3503.0,8.905130e+02,1.011238e+04,-6.534300e+03,1.100,37.100,2.023500e+02,3.901338e+05
Capital employed,3541.0,2.328348e+03,2.106901e+04,0.000000e+00,60.800,214.700,7.673000e+02,8.914089e+05
TOL/TNW,3541.0,3.993892e+00,1.939881e+01,-3.504800e+02,0.600,1.430,2.830000e+00,4.730000e+02
Total term liabilities / tangible net worth,3541.0,1.843886e+00,1.477312e+01,-3.256000e+02,0.050,0.340,1.000000e+00,4.560000e+02
Contingent liabilities / Net worth (%),3541.0,5.393829e+01,3.788354e+02,0.000000e+00,0.000,5.330,3.076000e+01,1.470427e+04
Contingent liabilities,2353.0,9.329194e+02,1.297332e+04,1.000000e-01,6.300,38.000,1.927000e+02,5.595068e+05
Net fixed assets,3423.0,1.189678e+03,1.329191e+04,0.000000e+00,26.000,93.500,3.448500e+02,6.366046e+05
Investments,2106.0,6.947343e+02,6.895539e+03,0.000000e+00,1.000,8.350,6.430000e+01,1.999786e+05
Current assets,3475.0,1.293364e+03,1.013177e+04,1.000000e-01,36.200,145.100,5.022500e+02,3.548152e+05
Net working capital,3509.0,1.385693e+02,2.945476e+03,-6.383900e+04,-1.100,16.200,8.420000e+01,8.578280e+04
Quick ratio (times),3448.0,1.401395e+00,7.729697e+00,0.000000e+00,0.410,0.670,1.030000e+00,3.410000e+02
Current ratio (times),3448.0,2.130409e+00,1.010807e+01,0.000000e+00,0.930,1.230,1.710000e+00,5.050000e+02
Debt to equity ratio (times),3541.0,2.779670e+00,1.497406e+01,0.000000e+00,0.220,0.790,1.750000e+00,4.560000e+02
Cash to current liabilities (times),3448.0,4.904002e-01,4.195739e+00,0.000000e+00,0.020,0.070,1.900000e-01,1.650000e+02
Cash to average cost of sales per day,3456.0,1.584435e+02,2.746900e+03,0.000000e+00,2.790,8.025,2.178750e+01,1.280408e+05
Creditors turnover,3208.0,1.544568e+01,6.820860e+01,0.000000e+00,3.700,6.095,1.149000e+01,2.401000e+03
Debtors turnover,3213.0,1.704126e+01,8.394375e+01,0.000000e+00,3.760,6.320,1.168000e+01,3.135200e+03
Finished goods turnover,2801.0,8.707873e+01,5.985458e+02,-9.000000e-02,8.200,17.270,4.035000e+01,1.794760e+04
WIP turnover,2901.0,2.793047e+01,1.510429e+02,-1.800000e-01,5.100,9.760,2.024000e+01,5.651400e+03
Raw material turnover,3180.0,1.908840e+01,3.763407e+02,-2.000000e+00,2.990,6.400,1.184500e+01,2.109200e+04
Shares outstanding,2849.0,2.206739e+07,1.655193e+08,-2.147484e+09,1316250.000,4672063.000,1.065197e+07,4.130401e+09
Equity face value,2849.0,-1.333698e+03,3.750073e+04,-9.999989e+05,10.000,10.000,1.000000e+01,1.000000e+05
EPS,3541.0,-2.203164e+02,1.426195e+04,-8.431818e+05,0.000,1.430,9.620000e+00,3.452253e+04
Adjusted EPS,3541.0,-2.215123e+02,1.426192e+04,-8.431818e+05,0.000,1.180,7.480000e+00,3.452253e+04
Total liabilities,3541.0,3.443382e+03,3.097089e+04,1.000000e-01,91.300,309.700,1.098700e+03,1.176509e+06
PE on BSE,1347.0,6.390569e+01,1.433810e+03,-1.116640e+03,3.275,9.100,1.779000e+01,5.100274e+04

In [66]:
data.columns

Index(['Num', 'Networth Next Year', 'Total assets', 'Net worth',
       'Total income', 'Change in stock', 'Total expenses', 'Profit after tax',
       'PBDITA', 'PBT', 'Cash profit', 'PBDITA as % of total income',
       'PBT as % of total income', 'PAT as % of total income',
       'Cash profit as % of total income', 'PAT as % of net worth', 'Sales',
       'Income from financial services', 'Other income', 'Total capital',
       'Reserves and funds', 'Deposits (accepted by commercial banks)',
       'Borrowings', 'Current liabilities & provisions',
       'Deferred tax liability', 'Shareholders funds',
       'Cumulative retained profits', 'Capital employed', 'TOL/TNW',
       'Total term liabilities / tangible net worth',
       'Contingent liabilities / Net worth (%)', 'Contingent liabilities',
       'Net fixed assets', 'Investments', 'Current assets',
       'Net working capital', 'Quick ratio (times)', 'Current ratio (times)',
       'Debt to equity ratio (times)', 'Cash to current liabilities (times)',
       'Cash to average cost of sales per day', 'Creditors turnover',
       'Debtors turnover', 'Finished goods turnover', 'WIP turnover',
       'Raw material turnover', 'Shares outstanding', 'Equity face value',
       'EPS', 'Adjusted EPS', 'Total liabilities', 'PE on BSE'],
      dtype='object')

##### Renaming the column names

In [67]:
data.columns = data.columns.str.replace(' ', '_')

In [68]:
data.columns

Index(['Num', 'Networth_Next_Year', 'Total_assets', 'Net_worth',
       'Total_income', 'Change_in_stock', 'Total_expenses', 'Profit_after_tax',
       'PBDITA', 'PBT', 'Cash_profit', 'PBDITA_as_%_of_total_income',
       'PBT_as_%_of_total_income', 'PAT_as_%_of_total_income',
       'Cash_profit_as_%_of_total_income', 'PAT_as_%_of_net_worth', 'Sales',
       'Income_from_financial_services', 'Other_income', 'Total_capital',
       'Reserves_and_funds', 'Deposits_(accepted_by_commercial_banks)',
       'Borrowings', 'Current_liabilities_&_provisions',
       'Deferred_tax_liability', 'Shareholders_funds',
       'Cumulative_retained_profits', 'Capital_employed', 'TOL/TNW',
       'Total_term_liabilities_/_tangible_net_worth',
       'Contingent_liabilities_/_Net_worth_(%)', 'Contingent_liabilities',
       'Net_fixed_assets', 'Investments', 'Current_assets',
       'Net_working_capital', 'Quick_ratio_(times)', 'Current_ratio_(times)',
       'Debt_to_equity_ratio_(times)', 'Cash_to_current_liabilities_(times)',
       'Cash_to_average_cost_of_sales_per_day', 'Creditors_turnover',
       'Debtors_turnover', 'Finished_goods_turnover', 'WIP_turnover',
       'Raw_material_turnover', 'Shares_outstanding', 'Equity_face_value',
       'EPS', 'Adjusted_EPS', 'Total_liabilities', 'PE_on_BSE'],
      dtype='object')

In [69]:
data.columns = data.columns.str.replace('(', '').str.replace(')', '').str.replace('%', 'perc').str.replace('/', 'to')

In [70]:
data.columns

Index(['Num', 'Networth_Next_Year', 'Total_assets', 'Net_worth',
       'Total_income', 'Change_in_stock', 'Total_expenses', 'Profit_after_tax',
       'PBDITA', 'PBT', 'Cash_profit', 'PBDITA_as_perc_of_total_income',
       'PBT_as_perc_of_total_income', 'PAT_as_perc_of_total_income',
       'Cash_profit_as_perc_of_total_income', 'PAT_as_perc_of_net_worth',
       'Sales', 'Income_from_financial_services', 'Other_income',
       'Total_capital', 'Reserves_and_funds',
       'Deposits_accepted_by_commercial_banks', 'Borrowings',
       'Current_liabilities_&_provisions', 'Deferred_tax_liability',
       'Shareholders_funds', 'Cumulative_retained_profits', 'Capital_employed',
       'TOLtoTNW', 'Total_term_liabilities_to_tangible_net_worth',
       'Contingent_liabilities_to_Net_worth_perc', 'Contingent_liabilities',
       'Net_fixed_assets', 'Investments', 'Current_assets',
       'Net_working_capital', 'Quick_ratio_times', 'Current_ratio_times',
       'Debt_to_equity_ratio_times', 'Cash_to_current_liabilities_times',
       'Cash_to_average_cost_of_sales_per_day', 'Creditors_turnover',
       'Debtors_turnover', 'Finished_goods_turnover', 'WIP_turnover',
       'Raw_material_turnover', 'Shares_outstanding', 'Equity_face_value',
       'EPS', 'Adjusted_EPS', 'Total_liabilities', 'PE_on_BSE'],
      dtype='object')

##### Networth_Next_Year is a target variable and it needs to be converted to categorical column as all the values in column is continuous

##### Wherever in column; value is >0, it will be updated as 0 else 1

In [71]:
data['Networth_Next_Year_1'] = np.where((data['Networth_Next_Year'] > 0), 0, 1)

In [72]:
data['Networth_Next_Year_1'].value_counts()

Networth_Next_Year_1
0    3298
1     243
Name: count, dtype: int64

In [73]:
data[['Networth_Next_Year', 'Networth_Next_Year_1']]

      Networth_Next_Year  Networth_Next_Year_1
0                 8890.6                     0
1                  394.3                     0
2                   92.2                     0
3                    2.7                     0
4                  109.0                     0
...                  ...                   ...
3536               226.4                     0
3537                89.4                     0
3538               246.2                     0
3539               146.9                     0
3540                -0.2                     1

[3541 rows x 2 columns]

In [74]:
(data.isnull().sum()/len(data)) * 100

Num                                               0.000000
Networth_Next_Year                                0.000000
Total_assets                                      0.000000
Net_worth                                         0.000000
Total_income                                      5.591641
Change_in_stock                                  12.934199
Total_expenses                                    3.925445
Profit_after_tax                                  3.699520
PBDITA                                            3.699520
PBT                                               3.699520
Cash_profit                                       3.699520
PBDITA_as_perc_of_total_income                    1.920361
PBT_as_perc_of_total_income                       1.920361
PAT_as_perc_of_total_income                       1.920361
Cash_profit_as_perc_of_total_income               1.920361
PAT_as_perc_of_net_worth                          0.000000
Sales                                             7.314318
Income_from_financial_services                   26.404970
Other_income                                     36.571590
Total_capital                                     0.112962
Reserves_and_funds                                2.400452
Deposits_accepted_by_commercial_banks           100.000000
Borrowings                                       10.336063
Current_liabilities_&_provisions                  2.711099
Deferred_tax_liability                           32.194295
Shareholders_funds                                0.000000
Cumulative_retained_profits                       1.073143
Capital_employed                                  0.000000
TOLtoTNW                                          0.000000
Total_term_liabilities_to_tangible_net_worth      0.000000
Contingent_liabilities_to_Net_worth_perc          0.000000
Contingent_liabilities                           33.549845
Net_fixed_assets                                  3.332392
Investments                                      40.525275
Current_assets                                    1.863880
Net_working_capital                               0.903700
Quick_ratio_times                                 2.626377
Current_ratio_times                               2.626377
Debt_to_equity_ratio_times                        0.000000
Cash_to_current_liabilities_times                 2.626377
Cash_to_average_cost_of_sales_per_day             2.400452
Creditors_turnover                                9.404123
Debtors_turnover                                  9.262920
Finished_goods_turnover                          20.898051
WIP_turnover                                     18.073990
Raw_material_turnover                            10.194860
Shares_outstanding                               19.542502
Equity_face_value                                19.542502
EPS                                               0.000000
Adjusted_EPS                                      0.000000
Total_liabilities                                 0.000000
PE_on_BSE                                        61.959898
Networth_Next_Year_1                              0.000000
dtype: float64

In [75]:
null.sort_values()

Num                                              0.000000
Adjusted EPS                                     0.000000
EPS                                              0.000000
Debt to equity ratio (times)                     0.000000
Contingent liabilities / Net worth (%)           0.000000
Total term liabilities / tangible net worth      0.000000
TOL/TNW                                          0.000000
Capital employed                                 0.000000
Total liabilities                                0.000000
PAT as % of net worth                            0.000000
Shareholders funds                               0.000000
Total assets                                     0.000000
Net worth                                        0.000000
Networth Next Year                               0.000000
Total capital                                    0.112962
Net working capital                              0.903700
Cumulative retained profits                      1.073143
Current assets                                   1.863880
PBDITA as % of total income                      1.920361
Cash profit as % of total income                 1.920361
PAT as % of total income                         1.920361
PBT as % of total income                         1.920361
Cash to average cost of sales per day            2.400452
Reserves and funds                               2.400452
Current ratio (times)                            2.626377
Quick ratio (times)                              2.626377
Cash to current liabilities (times)              2.626377
Current liabilities & provisions                 2.711099
Net fixed assets                                 3.332392
Cash profit                                      3.699520
PBT                                              3.699520
PBDITA                                           3.699520
Profit after tax                                 3.699520
Total expenses                                   3.925445
Total income                                     5.591641
Sales                                            7.314318
Debtors turnover                                 9.262920
Creditors turnover                               9.404123
Raw material turnover                           10.194860
Borrowings                                      10.336063
Change in stock                                 12.934199
WIP turnover                                    18.073990
Equity face value                               19.542502
Shares outstanding                              19.542502
Finished goods turnover                         20.898051
Income from financial services                  26.404970
Deferred tax liability                          32.194295
Contingent liabilities                          33.549845
Other income                                    36.571590
Investments                                     40.525275
PE on BSE                                       61.959898
Deposits (accepted by commercial banks)        100.000000
dtype: float64

##### Splitting the X and y

In [76]:
data_X = data.drop(['Networth_Next_Year_1'], axis = 1)
data_y = data['Networth_Next_Year_1']

##### Dropping columns : Num(all values are unique), Networth_Next_Year(already converted to categorical column), Deposits_accepted_by_commercial_banks(100% null values)

In [77]:
data_X.drop(['Num', 'Networth_Next_Year', 'Deposits_accepted_by_commercial_banks'], axis = 1, inplace = True)

##### In the dataset; columns(Other_income, Deferred_tax_liability, Contingent_liabilities, Investments, PE_on_BSE) consists null values >30%; hence dropping it as imputing such gaps may introduce biasness in the data.

In [78]:
drop_cols = data_X.columns[(data_X.isnull().mean()*100) >= 30]
print(drop_cols.tolist())

['Other_income', 'Deferred_tax_liability', 'Contingent_liabilities', 'Investments', 'PE_on_BSE']

In [79]:
data_X.drop(drop_cols, axis = 1, inplace = True)

In [80]:
data_X.head(1)

,Total_assets,Net_worth,Total_income,Change_in_stock,Total_expenses,Profit_after_tax,PBDITA,PBT,Cash_profit,PBDITA_as_perc_of_total_income,...,Creditors_turnover,Debtors_turnover,Finished_goods_turnover,WIP_turnover,Raw_material_turnover,Shares_outstanding,Equity_face_value,EPS,Adjusted_EPS,Total_liabilities
0,17512.3,7093.2,24965.2,235.8,23657.8,1543.2,2860.2,2417.2,1872.8,11.46,...,3.62,3.85,200.55,21.78,7.71,42381675.0,10.0,35.52,7.1,17512.3

In [81]:
(data_X.isnull().mean()*100).sort_values()

Total_assets                                     0.000000
EPS                                              0.000000
Debt_to_equity_ratio_times                       0.000000
Contingent_liabilities_to_Net_worth_perc         0.000000
Total_term_liabilities_to_tangible_net_worth     0.000000
TOLtoTNW                                         0.000000
Capital_employed                                 0.000000
Adjusted_EPS                                     0.000000
Shareholders_funds                               0.000000
PAT_as_perc_of_net_worth                         0.000000
Total_liabilities                                0.000000
Net_worth                                        0.000000
Total_capital                                    0.112962
Net_working_capital                              0.903700
Cumulative_retained_profits                      1.073143
Current_assets                                   1.863880
PAT_as_perc_of_total_income                      1.920361
Cash_profit_as_perc_of_total_income              1.920361
PBDITA_as_perc_of_total_income                   1.920361
PBT_as_perc_of_total_income                      1.920361
Reserves_and_funds                               2.400452
Cash_to_average_cost_of_sales_per_day            2.400452
Cash_to_current_liabilities_times                2.626377
Current_ratio_times                              2.626377
Quick_ratio_times                                2.626377
Current_liabilities_&_provisions                 2.711099
Net_fixed_assets                                 3.332392
Profit_after_tax                                 3.699520
PBDITA                                           3.699520
PBT                                              3.699520
Cash_profit                                      3.699520
Total_expenses                                   3.925445
Total_income                                     5.591641
Sales                                            7.314318
Debtors_turnover                                 9.262920
Creditors_turnover                               9.404123
Raw_material_turnover                           10.194860
Borrowings                                      10.336063
Change_in_stock                                 12.934199
WIP_turnover                                    18.073990
Shares_outstanding                              19.542502
Equity_face_value                               19.542502
Finished_goods_turnover                         20.898051
Income_from_financial_services                  26.404970
dtype: float64

##### Outlier Checking

In [82]:
q1 = data_X.quantile(0.25)
q3 = data_X.quantile(0.75)

iqr = q3 - q1

ul = q3 + 1.5 * iqr
ll = q1 - 1.5 * iqr

In [83]:
print(iqr)
print()
print(ul)
print()
print(ll)
print()

Total_assets                                    1.007400e+03
Net_worth                                       3.460000e+02
Total_income                                    1.334450e+03
Change_in_stock                                 1.985000e+01
Total_expenses                                  1.263950e+03
Profit_after_tax                                5.177500e+01
PBDITA                                          1.433500e+02
PBT                                             7.127500e+01
Cash_profit                                     9.030000e+01
PBDITA_as_perc_of_total_income                  1.139000e+01
PBT_as_perc_of_total_income                     8.250000e+00
PAT_as_perc_of_total_income                     5.990000e+00
Cash_profit_as_perc_of_total_income             8.680000e+00
PAT_as_perc_of_net_worth                        2.019000e+01
Sales                                           1.320875e+03
Income_from_financial_services                  9.275000e+00
Total_capital                                   8.720000e+01
Reserves_and_funds                              2.723000e+02
Borrowings                                      3.286500e+02
Current_liabilities_&_provisions                2.439000e+02
Shareholders_funds                              3.612000e+02
Cumulative_retained_profits                     2.012500e+02
Capital_employed                                7.065000e+02
TOLtoTNW                                        2.230000e+00
Total_term_liabilities_to_tangible_net_worth    9.500000e-01
Contingent_liabilities_to_Net_worth_perc        3.076000e+01
Net_fixed_assets                                3.188500e+02
Current_assets                                  4.660500e+02
Net_working_capital                             8.530000e+01
Quick_ratio_times                               6.200000e-01
Current_ratio_times                             7.800000e-01
Debt_to_equity_ratio_times                      1.530000e+00
Cash_to_current_liabilities_times               1.700000e-01
Cash_to_average_cost_of_sales_per_day           1.899750e+01
Creditors_turnover                              7.790000e+00
Debtors_turnover                                7.920000e+00
Finished_goods_turnover                         3.215000e+01
WIP_turnover                                    1.514000e+01
Raw_material_turnover                           8.855000e+00
Shares_outstanding                              9.335716e+06
Equity_face_value                               0.000000e+00
EPS                                             9.620000e+00
Adjusted_EPS                                    7.480000e+00
Total_liabilities                               1.007400e+03
dtype: float64

Total_assets                                    2.609800e+03
Net_worth                                       8.963000e+02
Total_income                                    3.442575e+03
Change_in_stock                                 4.782500e+01
Total_expenses                                  3.255700e+03
Profit_after_tax                                1.299375e+02
PBDITA                                          3.652750e+02
PBT                                             1.788875e+02
Cash_profit                                     2.286500e+02
PBDITA_as_perc_of_total_income                  3.347500e+01
PBT_as_perc_of_total_income                     2.117500e+01
PAT_as_perc_of_total_income                     1.532500e+01
Cash_profit_as_perc_of_total_income             2.372000e+01
PAT_as_perc_of_net_worth                        5.047500e+01
Sales                                           3.414863e+03
Income_from_financial_services                  2.358750e+01
Total_capital                                   2.311000e+02
Reserves_and_funds                              6.857500e+02
Borrowings                                      8.455750e+02
Current_liabilities_&_provisions                6.275500e+02
Shareholders_funds                              9.350000e+02
Cumulative_retained_profits                     5.042250e+02
Capital_employed                                1.827050e+03
TOLtoTNW                                        6.175000e+00
Total_term_liabilities_to_tangible_net_worth    2.425000e+00
Contingent_liabilities_to_Net_worth_perc        7.690000e+01
Net_fixed_assets                                8.231250e+02
Current_assets                                  1.201325e+03
Net_working_capital                             2.121500e+02
Quick_ratio_times                               1.960000e+00
Current_ratio_times                             2.880000e+00
Debt_to_equity_ratio_times                      4.045000e+00
Cash_to_current_liabilities_times               4.450000e-01
Cash_to_average_cost_of_sales_per_day           5.028375e+01
Creditors_turnover                              2.317500e+01
Debtors_turnover                                2.356000e+01
Finished_goods_turnover                         8.857500e+01
WIP_turnover                                    4.295000e+01
Raw_material_turnover                           2.512750e+01
Shares_outstanding                              2.465554e+07
Equity_face_value                               1.000000e+01
EPS                                             2.405000e+01
Adjusted_EPS                                    1.870000e+01
Total_liabilities                               2.609800e+03
dtype: float64

Total_assets                                   -1.419800e+03
Net_worth                                      -4.877000e+02
Total_income                                   -1.895225e+03
Change_in_stock                                -3.157500e+01
Total_expenses                                 -1.800100e+03
Profit_after_tax                               -7.716250e+01
PBDITA                                         -2.081250e+02
PBT                                            -1.062125e+02
Cash_profit                                    -1.325500e+02
PBDITA_as_perc_of_total_income                 -1.208500e+01
PBT_as_perc_of_total_income                    -1.182500e+01
PAT_as_perc_of_total_income                    -8.635000e+00
Cash_profit_as_perc_of_total_income            -1.100000e+01
PAT_as_perc_of_net_worth                       -3.028500e+01
Sales                                          -1.868638e+03
Income_from_financial_services                 -1.351250e+01
Total_capital                                  -1.177000e+02
Reserves_and_funds                             -4.034500e+02
Borrowings                                     -4.690250e+02
Current_liabilities_&_provisions               -3.480500e+02
Shareholders_funds                             -5.098000e+02
Cumulative_retained_profits                    -3.007750e+02
Capital_employed                               -9.989500e+02
TOLtoTNW                                       -2.745000e+00
Total_term_liabilities_to_tangible_net_worth   -1.375000e+00
Contingent_liabilities_to_Net_worth_perc       -4.614000e+01
Net_fixed_assets                               -4.522750e+02
Current_assets                                 -6.628750e+02
Net_working_capital                            -1.290500e+02
Quick_ratio_times                              -5.200000e-01
Current_ratio_times                            -2.400000e-01
Debt_to_equity_ratio_times                     -2.075000e+00
Cash_to_current_liabilities_times              -2.350000e-01
Cash_to_average_cost_of_sales_per_day          -2.570625e+01
Creditors_turnover                             -7.985000e+00
Debtors_turnover                               -8.120000e+00
Finished_goods_turnover                        -4.002500e+01
WIP_turnover                                   -1.761000e+01
Raw_material_turnover                          -1.029250e+01
Shares_outstanding                             -1.268732e+07
Equity_face_value                               1.000000e+01
EPS                                            -1.443000e+01
Adjusted_EPS                                   -1.122000e+01
Total_liabilities                              -1.419800e+03
dtype: float64

In [84]:
data_1 = pd.concat([data_X, data_y], axis = 1)
data_1.head(1)

,Total_assets,Net_worth,Total_income,Change_in_stock,Total_expenses,Profit_after_tax,PBDITA,PBT,Cash_profit,PBDITA_as_perc_of_total_income,...,Debtors_turnover,Finished_goods_turnover,WIP_turnover,Raw_material_turnover,Shares_outstanding,Equity_face_value,EPS,Adjusted_EPS,Total_liabilities,Networth_Next_Year_1
0,17512.3,7093.2,24965.2,235.8,23657.8,1543.2,2860.2,2417.2,1872.8,11.46,...,3.85,200.55,21.78,7.71,42381675.0,10.0,35.52,7.1,17512.3,0

##### Feature Scaling and Imputing the null values

In [85]:
predictors = data_1.drop('Networth_Next_Year_1', axis = 1)
response = data_1['Networth_Next_Year_1']

In [86]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [87]:
scaled_predictors = pd.DataFrame(scaler.fit_transform(predictors), columns = predictors.columns)
scaled_predictors.head(1)

,Total_assets,Net_worth,Total_income,Change_in_stock,Total_expenses,Profit_after_tax,PBDITA,PBT,Cash_profit,PBDITA_as_perc_of_total_income,...,Creditors_turnover,Debtors_turnover,Finished_goods_turnover,WIP_turnover,Raw_material_turnover,Shares_outstanding,Equity_face_value,EPS,Adjusted_EPS,Total_liabilities
0,0.454327,0.43309,0.366109,0.441112,0.365797,0.413139,0.403709,0.493965,0.350385,0.046834,...,-0.173402,-0.157168,0.189612,-0.040727,-0.030239,0.122752,0.035838,0.017941,0.016032,0.454327

In [88]:
data_2 = pd.concat([scaled_predictors, response], axis = 1)
data_2.head(1)

,Total_assets,Net_worth,Total_income,Change_in_stock,Total_expenses,Profit_after_tax,PBDITA,PBT,Cash_profit,PBDITA_as_perc_of_total_income,...,Debtors_turnover,Finished_goods_turnover,WIP_turnover,Raw_material_turnover,Shares_outstanding,Equity_face_value,EPS,Adjusted_EPS,Total_liabilities,Networth_Next_Year_1
0,0.454327,0.43309,0.366109,0.441112,0.365797,0.413139,0.403709,0.493965,0.350385,0.046834,...,-0.157168,0.189612,-0.040727,-0.030239,0.122752,0.035838,0.017941,0.016032,0.454327,0

In [89]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors = 5)
imputed_array = imputer.fit_transform(data_2)

In [90]:
data_imputed = pd.DataFrame(imputed_array, columns = data_2.columns)
data_imputed.head(1)

,Total_assets,Net_worth,Total_income,Change_in_stock,Total_expenses,Profit_after_tax,PBDITA,PBT,Cash_profit,PBDITA_as_perc_of_total_income,...,Debtors_turnover,Finished_goods_turnover,WIP_turnover,Raw_material_turnover,Shares_outstanding,Equity_face_value,EPS,Adjusted_EPS,Total_liabilities,Networth_Next_Year_1
0,0.454327,0.43309,0.366109,0.441112,0.365797,0.413139,0.403709,0.493965,0.350385,0.046834,...,-0.157168,0.189612,-0.040727,-0.030239,0.122752,0.035838,0.017941,0.016032,0.454327,0.0

In [91]:
data_imputed.isnull().sum()

Total_assets                                    0
Net_worth                                       0
Total_income                                    0
Change_in_stock                                 0
Total_expenses                                  0
Profit_after_tax                                0
PBDITA                                          0
PBT                                             0
Cash_profit                                     0
PBDITA_as_perc_of_total_income                  0
PBT_as_perc_of_total_income                     0
PAT_as_perc_of_total_income                     0
Cash_profit_as_perc_of_total_income             0
PAT_as_perc_of_net_worth                        0
Sales                                           0
Income_from_financial_services                  0
Total_capital                                   0
Reserves_and_funds                              0
Borrowings                                      0
Current_liabilities_&_provisions                0
Shareholders_funds                              0
Cumulative_retained_profits                     0
Capital_employed                                0
TOLtoTNW                                        0
Total_term_liabilities_to_tangible_net_worth    0
Contingent_liabilities_to_Net_worth_perc        0
Net_fixed_assets                                0
Current_assets                                  0
Net_working_capital                             0
Quick_ratio_times                               0
Current_ratio_times                             0
Debt_to_equity_ratio_times                      0
Cash_to_current_liabilities_times               0
Cash_to_average_cost_of_sales_per_day           0
Creditors_turnover                              0
Debtors_turnover                                0
Finished_goods_turnover                         0
WIP_turnover                                    0
Raw_material_turnover                           0
Shares_outstanding                              0
Equity_face_value                               0
EPS                                             0
Adjusted_EPS                                    0
Total_liabilities                               0
Networth_Next_Year_1                            0
dtype: int64

##### Importing all the necessary models/algorithms, evaluation metrics, hyperparameter tuning

In [102]:
from sklearn.model_selection import cross_val_score, GridSearchCV, KFold, RandomizedSearchCV, train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, r2_score, recall_score, f1_score, precision_score, roc_curve, auc
import statsmodels.formula.api as snf
from sklearn import tree

In [92]:
X_train, X_test, y_train, y_test = train_test_split(data_imputed.drop('Networth_Next_Year_1', axis = 1), data_imputed['Networth_Next_Year_1'], 
                                                    test_size = 0.25, random_state = 42)

In [93]:
X_train

,Total_assets,Net_worth,Total_income,Change_in_stock,Total_expenses,Profit_after_tax,PBDITA,PBT,Cash_profit,PBDITA_as_perc_of_total_income,...,Creditors_turnover,Debtors_turnover,Finished_goods_turnover,WIP_turnover,Raw_material_turnover,Shares_outstanding,Equity_face_value,EPS,Adjusted_EPS,Total_liabilities
490,-0.093659,-0.085176,-0.066737,-0.005651,-0.064434,-0.071006,-0.079367,-0.070476,-0.073276,0.070356,...,-0.065921,-0.118923,-0.118306,-0.121049,-0.031966,-0.107371,0.035838,0.016429,0.016513,-0.093659
3343,-0.110109,-0.094521,-0.081750,-0.098681,-0.080299,-0.090550,-0.102254,-0.093257,-0.092783,-0.031071,...,-0.226483,-0.203040,-0.144828,-0.184883,-0.050729,-0.114613,0.035838,0.015450,0.015534,-0.110109
1999,0.080316,0.170711,0.190498,0.313757,0.198108,0.105726,0.113400,0.148936,-0.024199,0.023517,...,-0.185573,1.728197,-0.133144,-0.142702,-0.045786,-0.070509,0.035838,0.018923,0.019007,0.080316
831,-0.100908,-0.084847,-0.071802,-0.071485,-0.069466,-0.085432,-0.095712,-0.088282,-0.086385,0.011892,...,0.057983,-0.101527,-0.029057,0.016022,-0.033003,-0.101924,0.035838,0.015660,0.015744,-0.100908
2023,0.138482,0.272078,-0.033758,0.132827,-0.045696,0.223874,0.112056,0.173010,0.156491,0.273549,...,-0.160645,-0.143228,-0.122717,-0.110322,-0.045653,0.216464,0.035624,0.016617,0.016117,0.138482
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,-0.101189,-0.089651,-0.076955,-0.097364,-0.074894,-0.088859,-0.096968,-0.091392,-0.087048,0.037045,...,-0.183520,-0.103434,0.032219,0.092437,0.013585,-0.109930,0.035838,0.015543,0.015626,-0.101189
1294,-0.058243,-0.038814,-0.032255,0.257912,-0.025781,-0.075445,-0.081525,-0.075310,-0.081321,-0.002452,...,1.527528,-0.032304,-0.114813,-0.151774,-0.012646,-0.103652,0.035838,0.016127,0.016211,-0.058243
860,-0.110490,-0.096486,-0.081667,-0.093278,-0.079720,-0.090360,-0.101939,-0.093092,-0.092514,0.002715,...,-0.191145,-0.130599,-0.124188,-0.119725,-0.023914,-0.126368,0.037278,0.015450,0.015534,-0.110490
3507,-0.068793,-0.065678,-0.036603,-0.189532,-0.033595,-0.083572,-0.080481,-0.082792,-0.073039,0.001831,...,-0.129706,-0.111178,-0.098838,-0.007817,-0.032179,-0.046475,0.036318,0.015449,0.015533,-0.068793
3174,0.378019,0.382641,0.201785,0.298320,0.191354,0.425476,0.384834,0.429686,0.319647,0.087283,...,-0.130292,-0.158360,-0.081677,0.004169,-0.029575,0.026785,0.035838,0.019670,0.016378,0.378019

In [94]:
y_train

490     0.0
3343    0.0
1999    0.0
831     0.0
2023    0.0
       ...
1130    0.0
1294    0.0
860     0.0
3507    0.0
3174    0.0
Name: Networth_Next_Year_1, Length: 2655, dtype: float64

In [95]:
y_train.value_counts()

Networth_Next_Year_1
0.0    2468
1.0     187
Name: count, dtype: int64

##### This is imbalanced dataset since there is huge difference between occurence of both classes. Hence, using SMOTE technique; we will balance the imbalanced dataset

In [96]:
import imblearn
from imblearn.over_sampling import SMOTE

In [97]:
data_imputed['Networth_Next_Year_1'] = np.where(data_imputed['Networth_Next_Year_1'] == 0.0, 0, 1)

In [98]:
sm = SMOTE(random_state = 42)
X_bal, y_bal = sm.fit_resample(X_train, y_train)

In [99]:
pred = data_imputed.drop('Networth_Next_Year_1', axis = 1)
res = data_imputed['Networth_Next_Year_1']

In [100]:
X_smote, y_smote = sm.fit_resample(pred, res)

In [101]:
y_bal.value_counts()

Networth_Next_Year_1
0.0    2468
1.0    2468
Name: count, dtype: int64

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X_smote, y_smote, test_size = 0.25, random_state = 42)

##### Model Building

In [105]:
# Logistic Regression
model_lor = LogisticRegression()
model_lor = model_lor.fit(X_train, y_train)
y_pred_lor = model_lor.predict(X_test)
accuracy_lor = accuracy_score(y_test, y_pred_lor)

# Random Forest
model_rf = RandomForestClassifier()
model_rf = model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)

# KNN
model_knn = KNeighborsClassifier()
model_knn = model_knn.fit(X_train, y_train)
y_pred_knn = model_knn.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)

In [106]:
accuracy_percent = pd.DataFrame({"Model" : ["Logistic Regression", "Random Forest", "KNN"], "Accuracy" : [accuracy_lor, accuracy_rf, accuracy_knn]})
accuracy_percent

                 Model  Accuracy
0  Logistic Regression  0.863554
1        Random Forest  0.969072
2                  KNN  0.947847

##### As per the table : Model vs Accuracy, we can see that the best accuracy we are receiving is from Random Forest model.

In [107]:
y_pred_rf_train = model_rf.predict(X_train)
print("Training Accuracy (Random Forest) : ", accuracy_score(y_train, y_pred_rf_train))
print("Testing Accuracy (Random Forest) : ", accuracy_rf)

Training Accuracy (Random Forest) :  1.0
Testing Accuracy (Random Forest) :  0.9690721649484536

In [109]:
cm = confusion_matrix(y_test, y_pred_rf)
cm

array([[798,  38],
       [ 13, 800]], dtype=int64)